### ISSUE TITLE
Yazi images preview pixelated

### ISSUE THREAD

**Issue by rodhash** [Rolv-Apneseth/tfm.nvim#9] opened 2024-03-02 15:35 UTC
Hi

Images preview are working fine on iTerm2 when using Yazi.. but when running this plugin images get pixelated

Nvim config:
```lua
  {
    "Rolv-Apneseth/tfm.nvim",
    config = function()
      -- Set keymap so you can open the default terminal file manager (yazi)
      vim.api.nvim_set_keymap("n", "<leader>e", "", {
        noremap = true,
        callback = require("tfm").open,
      })
    end,
  },
```

ueberzugpp config (tried all possible values for output but same result):
```json
{
  "layer": {
    "silent": true,
    "use-escape-codes": false,
    "no-stdin": false,
    "output": "sixel"
  }
}
```

Any idea why image preview is getting pixelated?

Thanks

**Comment by Rolv-Apneseth** [comment] 2024-03-14 00:25
Hey, sorry I haven't been getting any notifications for this repo, my bad.

I have no idea why that would be happening though, my guess would be it's Neovim related at that stage. All this plugin is doing is opening a terminal window within neovim. I would have assumed it would work the exact same, but maybe neovim isn't using the same protocol that `yazi` by itself is on `iTerm2`.

What happens with the image previews if you just do `:term` and call `yazi` in there? I assume that would still be blurry.

Sorry I can't be of more assistance, I don't know much about all the image previewing side of things.

**Comment by Rolv-Apneseth** [comment] 2024-03-14 10:21
Maybe it's using [chafa](https://hpjansson.org/chafa/) for some reason? It's listed as the fallback for `yazi` [here](https://yazi-rs.github.io/docs/image-preview)

**Comment by fmorroni** [comment] 2024-03-16 06:24
Probably related, on kitty image preview is not working at all when inside neovim. But it doesn't work when running it from within `:term` either.

**Comment by Rolv-Apneseth** [comment] 2024-03-16 11:58
Yeah sorry, I'm not sure. There appears to be an open issue for neovim about supporting the kitty image protocol here: https://github.com/neovim/neovim/issues/12991

It seems to not be able to fall back to any of the other options though, and I wouldn't know why. Did you try check ueberzugpp works by itself using the recommended method [in Yazi's documentation](https://yazi-rs.github.io/docs/image-preview#why-cant-i-preview-images-via-%C3%BCberzug)?

**Comment by rodhash** [comment] 2024-03-16 12:38
> What happens with the image previews if you just do `:term` and call `yazi` in there?

Just tried this and Yazi seems unable to preview images when running inside `:term`

**Comment by Rolv-Apneseth** [comment] 2024-03-17 00:24
> It seems to not be able to fall back to any of the other options though, and I wouldn't know why. Did you try check ueberzugpp works by itself using the recommended method [in Yazi's documentation](https://yazi-rs.github.io/docs/image-preview#why-cant-i-preview-images-via-%C3%BCberzug)?

Sorry @rodhash this was meant for you. Maybe if there's an issue with `ueberzugpp` then it makes it have to fall back to `chafa`. 

> Just tried this and Yazi seems unable to preview images when running inside `:term`

I believe then that the issue isn't specifically with this plugin so I'll be closing this. Sorry I can't help more, I don't know much about the actual implementation of image previewing within Neovim.

**Closed by Rolv-Apneseth** 2024-03-17 00:24 UTC

**Comment by rodhash** [comment] 2024-03-17 02:25
> > It seems to not be able to fall back to any of the other options though, and I wouldn't know why. Did you try check ueberzugpp works by itself using the recommended method [in Yazi's documentation](https://yazi-rs.github.io/docs/image-preview#why-cant-i-preview-images-via-%C3%BCberzug)?
> 
> 
> 
> Sorry @rodhash this was meant for you. Maybe if there's an issue with `ueberzugpp` then it makes it have to fall back to `chafa`. 
> 
> 
> 
> > Just tried this and Yazi seems unable to preview images when running inside `:term`
> 
> 
> 
> I believe then that the issue isn't specifically with this plugin so I'll be closing this. Sorry I can't help more, I don't know much about the actual implementation of image previewing within Neovim.

Sure no worries, thanks

**Comment by StitiFatah** [comment] 2024-03-20 04:50
> Probably related, on kitty image preview is not working at all when inside neovim. But it doesn't work when running it from within `:term` either.

@fmorroni it does work if you install ueberzugpp, although the package isn't needed when outside of neovim

**Comment by fmorroni** [comment] 2024-03-20 04:55
@StitiFatah haven't tried ueberzugpp but from what I've read it's way less performant than the kitty graphics protocol, so I'm not really interested in trying it.

**Comment by StitiFatah** [comment] 2024-03-20 04:57
> @StitiFatah haven't tried ueberzugpp but from what I've read it's way less performant than the kitty graphics protocol, so I'm not really interested in trying it.

@fmorroni maybe theoretically, seems pretty much instant to me nonetheless.
